;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-advanced-reader.ss" "lang")((modname Euler-29) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #t #t none #f ())))

;; Project Euler - Problem #29
;; Solved by Ali Ukani on May 20, 2011
;; "How many distinct terms are in the sequence
;;    generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?"

(require racket)

;; Given n, computes all unique terms in the sequence generated by a^b for 2 ≤ a ≤ n and 2 ≤ b ≤ n
(define (compute n)
  (local [(define range (build-list (- n 1) (λ (i) (+ i 2))))]
  (remove-duplicates (for*/list ([a range]
                                       [b range])
                             (expt a b)))))

(check-expect (sort (compute 5) <) (list 4 8 9 16 25 27 32 64 81 125 243 256 625 1024 3125))

(length (compute 100))

;; Run-time: 0.024 seconds